---
abstract: "Decouple code from imported functions"
author:
  - 'Montgomery Conner <dev@namimedia.com>'
build_requires:
  Test::Deep: 0
  Test::Differences: 0
  Test::Exception: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Devel-Decouple
no_index:
  directory:
    - t
    - inc
requires:
  Class::Inspector: 0
  Monkey::Patch: 0
  PPI::Document: 0
  PPI::Find: 0
  version: 0
version: v0.0.3
